- src/entity/CommonUser.java
- src/entity/CommonUserFactory.java
- src/entity/User.java
- src/entity/UserFactory.java
Added User and UserFactory interface, CommonUserFactory and CommonUser classes.
> User entity

- src/entity/CommonEventFactory.java
- src/entity/EventFactory.java
> kevinyyyeh

- .gitignore
- cheatSheet.md
- pom.xml
- src/config.properties
- src/daos/UserDAO.java
- src/database/MongoDBConnection.java
- src/test/java/UserDAOTest.java
> added mongodb dependency to pom.xml

- LinkUp.iml
- pom.xml
> change scope of junit to compile

- src/config.properties
> Remove config.properties from tracking

- LinkUp.iml
- src/daos/UserDAO.java
- src/test/java/UserDAOTest.java
userDAO update
---
---
---
---
> updated userDAO

- src/controllers/AccountCreationController.java
- src/controllers/UserController.java
- src/usecases/account_creation/AccountCreationInputBoundary.java
> Created accountcreationcontroller

- src/interface_adapter/AccountCreation/AccountCreationState.java
- src/interface_adapter/AccountCreation/AccountCreationViewModel.java
- src/interface_adapter/ViewModel.java
> created account creation viewmodel

- src/daos/GroupDAO.java
- src/entity/CommonGroup.java
- src/entity/CommonGroupFactory.java
- src/entity/CommonMessage.java
- src/entity/CommonMessageFactory.java
- src/entity/Group.java
- src/entity/GroupFactory.java
- src/entity/Message.java
- src/entity/MessageFactory.java
> added groupDAO, GroupFactory, MessageFactory

- src/usecases/login/LoginInputBoundary.java
- src/usecases/login/LoginInputData.java
- src/usecases/login/LoginInteractor.java
- src/usecases/login/LoginOutputBoundary.java
- src/usecases/login/LoginOutputData.java
- src/usecases/login/LoginUserDataAccessInterface.java
> Added login usecase

- src/test/java/views/test_accountCreationView.java
- src/usecases/account_creation/AccountCreationInputBoundary.java
- src/usecases/account_creation/AccountCreationInteractor.java
- src/views/AccountCreationView.java
- src/views/LoginView.java
> Created view for account creation and added testcases

- src/app/AppBuilder.java
- src/app/Main.java
- src/interface_adapter/AccountCreation/AccountCreationPresenter.java
- src/interface_adapter/AccountCreation/AccountCreationState.java
- src/interface_adapter/Login/LoginPresenter.java
- src/interface_adapter/Login/LoginState.java
- src/interface_adapter/ViewManagerModel.java
- src/views/AccountCreationView.java
- src/views/ViewManager.java
> Implemented viewmodel

- .gitignore
- src/app/AppBuilder.java
- src/app/Main.java
- src/interface_adapter/AccountCreation/AccountCreationPresenter.java
- src/interface_adapter/AccountCreation/AccountCreationViewModel.java
- src/interface_adapter/Login/LoginViewModel.java
- src/interface_adapter/ViewManagerModel.java
- src/interface_adapter/ViewModel.java
- src/views/AccountCreationView.java
- src/views/LoginView.java
- src/views/ViewManager.java
> Accomodation to integrate Login View to the code 

- .gitignore
- src/interface_adapter/AccountCreation/AccountCreationPresenter.java
- src/interface_adapter/AccountCreation/AccountCreationState.java
- src/interface_adapter/ViewModel.java
- src/usecases/account_creation/AccountCreationInteractor.java
- src/views/AccountCreationView.java
Added Error Handling for Sign-up Errors
---
I added error messages that get flashed whenever a signup error occurs.
The signup errors are as follows:
- Missing text fields
- Username already exists in database
- Repeated password does not equal password
---
- Error messages now get flashed for signup errors 
---
---
> added error handling for sign-up errors

- src/app/AppBuilder.java
- src/views/GroupChatView.java
… rapid and initialize earlier
Set default view to Login
---
I have changed the default view to be login, as requested by the review in #43 . Additionally, I made chat refreshing more rapid as well as to have an initial refresh based on @Lakssito's request.
---
> Set default view to loginview

- src/app/AppBuilder.java
- src/daos/CalendarDAO.java
- src/daos/MongoDAO.java
- src/interface_adapter/GroupChat/GroupChatViewModel.java
- src/test/java/MongoDAOTest.java
- src/usecases/message_translation/MessageTranslationInteractor.java
renamed UserGroupDAO to MongoDAO, removed unused CalendarDAO
---
Completed refactoring tasks as described in #46 
---
> renamed UserGroupDAO to MongoDAO, removed unused CalendarDAO

- src/views/GroupChatView.java
…keLater)
adjusted threaded message display updater to be a promise event 
---
Utilized SwingUtilities.invokeLater to asynchronously call displayMessages(), fixing an issue with glitchy message displays.
---
> adjusted threaded message display updater to be a promise event 

- src/views/UserSettingsView.java
> Added Default Time

- src/daos/MongoDAO.java
- src/interface_adapter/MessageTranslation/MessageTranslationController.java
- src/usecases/message_translation/MessageTranslationDataAccessInterface.java
- src/usecases/message_translation/MessageTranslationInputData.java
- src/usecases/message_translation/MessageTranslationInteractor.java
- src/views/GroupChatView.java
Database Refactoring for Translations
---
Key Changes:
- Database Layer Updates:
- Refactored getTranslatedMessage and saveTranslation to handle group-specific translations.
Integrated group-specific logic into groupCollection for storing and retrieving translations.
Data Access Interface Updates:
- Modified MessageTranslationDataAccessInterface to include group parameters in relevant methods.
- Removed redundant messageAlreadyTranslated method for simplified logic.
- Interactor Enhancements:
- Updated translation flow to check for and save group-specific translations.
- Improved validation logic for determining translation eligibility.
- Controller and View Adjustments:
- Simplified MessageTranslationController to align with the updated database logic.
- Updated GroupChatView to handle …
> Database Refactoring for Translations

- src/app/AppBuilder.java
- src/app/Main.java
- src/daos/MongoDAO.java
- src/interface_adapter/AddFriend/AddFriendController.java
- src/interface_adapter/AddFriend/AddFriendPresenter.java
- src/interface_adapter/AddFriend/AddFriendState.java
- src/interface_adapter/AddFriend/AddFriendViewModel.java
- src/usecases/account_creation/AccountCreationOutputData.java
- src/usecases/add_friend/AddFriendDataAccessInterface.java
- src/usecases/add_friend/AddFriendInputBoundary.java
- src/usecases/add_friend/AddFriendInputData.java
- src/usecases/add_friend/AddFriendInteractor.java
- src/usecases/add_friend/AddFriendOutputBoundary.java
- src/usecases/add_friend/AddFriendOutputData.java
- src/views/UserSettingsView.java
- src/views/ViewManager.java
> Add friend usecase

- src/views/GroupChatView.java
---
Implemented multithreading for the message sending process using ExecutorService. This change ensures that messages are sent asynchronously, enhancing application responsiveness and speeding up the process by offloading it to separate threads.
> Add Multithreading for Message Sending to Improve Performance

- src/usecases/add_friend/AddFriendInteractor.java
> Fixed bug in view

- src/views/GroupChatView.java
Updated chat font size
---
updated font size of chat messagaes to 16, and bolded the username of the sender
---
> Updated chat font size

- src/views/GroupChatView.java
> fixed sender name

- src/views/AccountCreationView.java
Updated language selection for account creation to be a dropdown menu
---
Rather than typing in a string of the language you are creating your account with, you now choose from a downdown menu of supported languages. The displayed languages are the full language names as Strings, where they are associated to the language code which is actually passed in as an input.
---
> Updated language selection for account creation to be a dropdown menu

- src/app/AppBuilder.java
- src/app/Main.java
- src/daos/MongoDAO.java
- src/interface_adapter/ChangeLanguage/ChangeLanguageController.java
- src/interface_adapter/ChangeLanguage/ChangeLanguagePresenter.java
- src/interface_adapter/ChangeLanguage/ChangeLanguageState.java
- src/interface_adapter/ChangeLanguage/ChangeLanguageViewModel.java
- src/usecases/change_language/ChangeLanguageDataAccessInterface.java
- src/usecases/change_language/ChangeLanguageInputBoundary.java
- src/usecases/change_language/ChangeLanguageInputData.java
- src/usecases/change_language/ChangeLanguageInteractor.java
- src/usecases/change_language/ChangeLanguageOutputBoundary.java
- src/usecases/change_language/ChangeLanguageOutputData.java
- src/views/GroupChatView.java
- src/views/UserSettingsView.java
Change User Language
---
---
---
---
> Added Change User Language

- src/views/GroupChatView.java
Group name label displaying group name
---
The group name label now correctly displays the name of the current group.
---
> Updated group name label to display current group

- src/daos/MongoDAO.java
- src/views/GroupChatView.java
Improved Group Switching and Optimized Message Display
---
This pull request enhances the GroupChatView functionality by addressing performance bottlenecks during group switches and improving the mechanism for displaying messages. The changes aim to create a smoother user experience by resolving glitches caused by rapid group changes and optimizing the display process to handle bulk message updates efficiently.
---
Group Switching Improvements:
Prevented glitches when rapidly switching between groups by implementing synchronized processes for updating the currentGroup and clearing/reloading the chat panel.
Added a loading indicator for a better UX while fetching messages for the selected group.
Message Display Enhancements:
Optimized the bulk addition of messages to the chat panel to …
> Improved Group Switching and Optimized Message Display

- src/views/AccountCreationView.java
Account Creation View
---
---
---
---
> Account Creation View with dropdown

- src/views/AccountCreationView.java
> Revert "un-commented line related to dropdown menu for language selection dur…"

- src/app/AppBuilder.java
- src/app/Main.java
- src/daos/MongoDAO.java
- src/interface_adapter/RemoveFriend/RemoveFriendController.java
- src/interface_adapter/RemoveFriend/RemoveFriendPresenter.java
- src/interface_adapter/RemoveFriend/RemoveFriendState.java
- src/interface_adapter/RemoveFriend/RemoveFriendViewModel.java
- src/usecases/remove_friend/RemoveFriendDataAccessInterface.java
- src/usecases/remove_friend/RemoveFriendInputBoundary.java
- src/usecases/remove_friend/RemoveFriendInputData.java
- src/usecases/remove_friend/RemoveFriendInteractor.java
- src/usecases/remove_friend/RemoveFriendOutputBoundary.java
- src/usecases/remove_friend/RemoveFriendOutputData.java
- src/views/UserSettingsView.java
Add RemoveFriend Use Case
---
This PR introduces the "Remove Friend" functionality to the application, allowing users to remove friends from their friend list. The implementation spans across several layers of the application, ensuring a clean architecture and proper integration into existing modules.
---
Major Changes:
- Added the RemoveFriendController, RemoveFriendPresenter, RemoveFriendViewModel, and RemoveFriendState to the interface_adapter layer.
- Created new interfaces (RemoveFriendInputBoundary, RemoveFriendOutputBoundary, RemoveFriendDataAccessInterface) and their implementations (RemoveFriendInteractor and MongoDAO) in the usecases layer.
- Updated UserSettingsView to support the new "Remove Friend" feature, including UI elements and event handling.
Integrated the use case …
> Add RemoveFriend Use Case

- src/app/AppBuilder.java
- src/app/Main.java
- src/daos/MongoDAO.java
- src/interface_adapter/AddGroupMember/AddGroupMemberController.java
- src/interface_adapter/AddGroupMember/AddGroupMemberPresenter.java
- src/interface_adapter/AddGroupMember/AddGroupMemberState.java
- src/interface_adapter/AddGroupMember/AddGroupMemberViewModel.java
- src/usecases/add_group_member/AddGroupMemberDataAccessInterface.java
- src/usecases/add_group_member/AddGroupMemberInputBoundary.java
- src/usecases/add_group_member/AddGroupMemberInputData.java
- src/usecases/add_group_member/AddGroupMemberInteractor.java
- src/usecases/add_group_member/AddGroupMemberOutputBoundary.java
- src/usecases/add_group_member/AddGroupMemberOutputData.java
- src/views/GroupSettingsView.java
Implemented the AddGroupMember usecase and updated the existing files when necessary (Main, AppBuilder, MongoDAO and GroupSettingsView).
---
This adds and implements all the files for the interface adapter of the AddGroupMember usecase.
---
---
---
Let me know what you think about these files.
> Add group member usecase added

- src/app/AppBuilder.java
- src/daos/MongoDAO.java
> Fixed samy's changes

- src/test/java/entities/CommonUserTest.java
- src/test/java/usecases/add_group_event/AddGroupEventInteractorTest.java
- src/test/java/usecases/delete_group_event/DeleteGroupEventInteractorTest.java
- src/test/java/usecases/modify_group_name/ModifyGroupNameInteractorTest.java
- src/usecases/modify_group_name/ModifyGroupNameOutputData.java
Test Cases for Delete Group Event and Modify Group Name
---
This PR introduces comprehensive test cases to ensure robustness and accuracy of functionality in the `DeleteGroupEventInteractor` and `ModifyGroupNameInteractor`. It addresses remaining use cases for deleting group events and modifying group names, enhancing the test coverage and reinforcing reliability for edge scenarios. Additionally, minor updates have been made to the `ModifyGroupNameOutputData` class.
---
- **New Tests Added**:
- **DeleteGroupEventInteractorTest**:
- `testExecuteSuccess`: Verifies successful deletion of a group event.
- `testExecuteWithDifferentTimes`: Ensures correct handling of varying event times.
- `testExecuteWithEmptyFields`: Tests input with missing fields.
- `testExecuteWithSpecialCharacters`: …
> created testcases for delete group event and modify group name
